# Generated by Django 4.1.3 on 2023-05-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('auditoriumid', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_of_auditorium', models.CharField(max_length=8)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'auditorium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultationid', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=300)),
                ('date', models.DateField(db_column='Date')),
                ('start_time', models.TimeField(db_column='Start_time')),
                ('end_time', models.TimeField(db_column='End_time')),
                ('was_conducted', models.CharField(blank=True, db_column='Was_conducted', max_length=3, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=400, null=True)),
            ],
            options={
                'db_table': 'consultation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.BigAutoField(db_column='departmentID', primary_key=True, serialize=False)),
                ('title_of_department', models.CharField(db_column='Title_of_department', max_length=350)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('disciplineid', models.BigIntegerField(db_column='disciplineID', primary_key=True, serialize=False)),
                ('name_of_discipline', models.CharField(db_column='Name_of_discipline', max_length=300)),
            ],
            options={
                'db_table': 'discipline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyid', models.BigAutoField(db_column='facultyID', primary_key=True, serialize=False)),
                ('title_of_faculty', models.CharField(db_column='Title_of_faculty', max_length=350)),
                ('abbreviated_name_of_faculty', models.CharField(db_column='Abbreviated_name_of_faculty', max_length=10)),
            ],
            options={
                'db_table': 'faculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_of_group', models.CharField(db_column='Number_of_group', max_length=10)),
                ('year_of_entry', models.IntegerField(db_column='Year_of_entry')),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturerid', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_name_lecturer', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_lecturer', models.CharField(max_length=50)),
                ('patronymic_lecturer', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lecturer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('positionid', models.BigAutoField(db_column='PositionID', primary_key=True, serialize=False)),
                ('title_of_position', models.CharField(db_column='Title_of_position', max_length=50)),
            ],
            options={
                'db_table': 'Positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('student_recordid', models.BigAutoField(db_column='Student_recordID', primary_key=True, serialize=False)),
                ('visiting', models.CharField(blank=True, db_column='Visiting', max_length=3, null=True)),
                ('notes_of_lecturer', models.CharField(blank=True, db_column='Notes_of_lecturer', max_length=400, null=True)),
            ],
            options={
                'db_table': 'Student record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentid', models.BigAutoField(primary_key=True, serialize=False)),
                ('last_name_student', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name_student', models.CharField(max_length=50)),
                ('patronymic_student', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_record_book', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfAuditorium',
            fields=[
                ('type_of_auditoriumid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_of_auditorium', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'type_of_auditorium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityBuilding',
            fields=[
                ('university_buildingid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_of_building', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'university_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.BigAutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('login', models.CharField(db_column='Login', max_length=50)),
                ('password', models.CharField(db_column='Password', max_length=50)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
